name: "Update cachix cache for Orchestrating Microbiome Analysis environment"

on:
  push:
    branches: [ master, main ]
jobs:
  r-update-cachix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=https://github.com/rstats-on-nix/nixpkgs/archive/1cc45486706aa5b124e667c5fd57c19900750bff.tar.gz
  
    - uses: cachix/cachix-action@v14
      with:
        name: oma
        # If you chose signing key for write access
        # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH }}'
  
    - run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              nix-build --argstr system x86_64-linux
              nix-build --argstr system aarch64-linux
         else
              nix-build
         fi
        
    - run: nix-store -qR --include-outputs $(nix-instantiate default.nix) | cachix push oma
    - run: nix-shell --run "echo OK"
